#!/usr/bin/env python3
"""Ingest the documents THIS project generated (papers, preregistrations,
results, roadmaps, reviews, lessons learned) into ANSE's Chroma store.

Kept apart from the literature on purpose: collection `adscmt_generated`, never
`adscmt_literature`. A retrieval hit must say whether it is published
literature or our own (possibly unreviewed) writing, and every record carries
`source_kind`, `path`, `git_commit`, `sha256` and, when the ledger has one,
the evidence tier of the document's claims.

Same embedder and same fail-closed rule as ingest_chroma.py (ANSE's
OllamaEmbeddingFunction; no hash-embedding fallback). Deterministic ids
`gen::<path>::<n>` with upsert; a document whose sha256 changed is re-chunked
and its stale chunks deleted.

    python3 corpus/ingest_generated.py [--dry-run]
"""
from __future__ import annotations

import argparse
import hashlib
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from ingest_chroma import (  # noqa: E402
    DEFAULT_CHROMA_PATH, chunk, clean, extract_pdf_text, load_anse_embedding_function,
)

ROOT = Path(__file__).resolve().parent.parent
COLLECTION = "adscmt_generated"
EXCLUDE = ("papers/", ".claude/", "node_modules/", "release/build/", "docs/elenchus/evidence/")

# (glob, source_kind); first match wins
SOURCES = [
    ("experiments/track_h_hyperbolic_network/paper/main.pdf", "paper_pdf"),
    ("**/PREREGISTRATION*.md", "preregistration"),
    ("**/RESULTS.md", "results"),
    ("**/results.md", "results"),
    ("**/HYPOTHESIS.md", "hypothesis"),
    ("LL.md", "lessons_learned"),
    ("docs/roadmap*.md", "roadmap"),
    ("docs/*review*.md", "literature_review"),
    ("docs/*.md", "doc"),
    ("experiments/**/*.md", "experiment_doc"),
    ("README.md", "readme"),
]


def git_commit() -> str:
    r = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, capture_output=True, text=True)
    return r.stdout.strip() or "unknown"


def tracked(path: Path) -> bool:
    r = subprocess.run(["git", "ls-files", "--error-unmatch", str(path.relative_to(ROOT))], cwd=ROOT,
                       capture_output=True)
    return r.returncode == 0


def collect() -> list[tuple[Path, str]]:
    seen, out = set(), []
    for pattern, kind in SOURCES:
        for p in sorted(ROOT.glob(pattern)):
            rel = str(p.relative_to(ROOT))
            if p in seen or not p.is_file() or any(rel.startswith(e) or f"/{e}" in rel for e in EXCLUDE):
                continue
            if not tracked(p):
                continue  # only committed documents: a retrieval hit must be reproducible from git
            seen.add(p)
            out.append((p, kind))
    return out


def text_of(p: Path) -> str:
    if p.suffix == ".pdf":
        return extract_pdf_text(p, max_pages=40)
    t = p.read_text(encoding="utf-8", errors="replace")
    return clean(re.sub(r"<!--.*?-->", "", t, flags=re.S))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--chroma-path", default=DEFAULT_CHROMA_PATH)
    ap.add_argument("--collection", default=COLLECTION)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--batch-size", type=int, default=4)
    ap.add_argument("--timeout", type=float, default=900)
    a = ap.parse_args()

    commit = git_commit()
    docs = collect()
    records = []
    for p, kind in docs:
        body = text_of(p)
        if not body:
            continue
        rel = str(p.relative_to(ROOT))
        digest = hashlib.sha256(p.read_bytes()).hexdigest()
        for n, piece in enumerate(chunk(body)):
            records.append((f"gen::{rel}::{n}", f"[generated | {kind} | {rel}]\n\n{piece}",
                            {"corpus": "adscmt_generated", "source_kind": kind, "path": rel, "chunk": n,
                             "git_commit": commit, "sha256": digest,
                             "provenance": "generated by this project; NOT peer-reviewed literature"}))
    print(f"{len(docs)} documents -> {len(records)} chunks (commit {commit})")
    if a.dry_run:
        for p, kind in docs:
            print(f"  {kind:18} {p.relative_to(ROOT)}")
        return 0

    embedder = load_anse_embedding_function()(timeout_s=a.timeout, max_retries=2)
    probe = embedder.probe()
    print(f"embeddings: {probe['model']} -> {probe['dimension']}-d", flush=True)
    import chromadb
    col = chromadb.PersistentClient(path=a.chroma_path).get_or_create_collection(
        name=a.collection, embedding_function=embedder, metadata={"hnsw:space": "cosine"})

    # drop chunks of documents that changed or disappeared
    keep_ids = {r[0] for r in records}
    existing = col.get(include=["metadatas"])
    stale = [i for i, m in zip(existing["ids"], existing["metadatas"])
             if i not in keep_ids or m.get("sha256") != next((r[2]["sha256"] for r in records if r[0] == i), None)]
    fresh = {i for i, m in zip(existing["ids"], existing["metadatas"])} - set(stale)
    if stale:
        col.delete(ids=stale)
        print(f"removed {len(stale)} stale chunks")
    todo = [r for r in records if r[0] not in fresh]
    for s in range(0, len(todo), a.batch_size):
        b = todo[s:s + a.batch_size]
        col.upsert(ids=[r[0] for r in b], documents=[r[1] for r in b], metadatas=[r[2] for r in b])
        print(f"  upserted {min(s + a.batch_size, len(todo))}/{len(todo)}", flush=True)
    print(f"collection '{a.collection}' holds {col.count()} chunks; store {a.chroma_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
